# Lang
language: zh-CN

# Header
menu:
  Home: /
  Archives: /archives
  # Life: /collection
  About: /about
rss: /atom.xml

# Content
fancybox: true


# Miscellaneous
google_analytics:
baidu_tongji: true
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:


# Profile
nickname: Yifan
description: 写代码的艺术家
links:
  Blog: /archives
  GitHub: https://github.com/zhuyifan2013
  Weibo: http://weibo.com/u/1830762480
  Mail: mailto:zhu_yifan@qq.com

# Info
archive_footer_content: Yifan
post_footer_content: Yifan
